# Generated by Django 5.2.3 on 2025-06-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudanalysis',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
