# Generated by Django 5.2.1 on 2025-05-26 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloudanalysis',
            old_name='cloud_color',
            new_name='values',
        ),
    ]
