# Generated by Django 5.2.1 on 2025-05-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_rename_cloud_color_cloudanalysis_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudanalysis',
            name='type',
            field=models.CharField(default='radar+', max_length=50),
        ),
    ]
