# Generated by Django 5.2.1 on 2025-05-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_cloudanalysis_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudanalysis',
            name='type',
            field=models.CharField(default='Radar+', max_length=50),
        ),
    ]
