# Generated by Django 5.2.1 on 2025-05-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_alter_cloudanalysis_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudanalysis',
            name='type',
            field=models.CharField(default='Weather radar', max_length=50),
        ),
    ]
